### ISSUE TITLE
Name proposal

### ISSUE THREAD

**Issue by RiordanIX** [tomsmeding/editor#16]
Hello,
I was looking for a basic text editor and found this project. It's simple enough to wrap my head around and doesn't have a thousand dependencies, which I love!

I was wondering if you were looking for a name for it. If so, I would like to propose the name "Smeditor", after the original author. I think it has the perfect amount of cheese.

Thanks for the consideration.

**Comment by tomsmeding** [comment]
Haha thanks :) I also don't like projects that have lots and lots of dependencies (think Node.JS culture), so that's why all of my projects have, like, at most one... (well except my Node.JS projects. There it's just impossible.)
I personally think "Smeditor" is a bit too cheesy, but yeah. Thanks for the suggestion, but I'll continue looking...

I see you've looked at the code some more and made some changes. Thanks!
Were you aware of [this](http://antirez.com/news/108)? It's supposed to be a really tiny and hackable editor. I haven't really looked into it much, but maybe it's interesting as well?

**Comment by RiordanIX** [comment]
I checked it out and it is very neat. Thanks for the info!
